[project]
name = "spei"
version = "0.2.3"
authors = [{ name = "Martin Vonk" }]
description = "A simple Python package to calculate drought indices for time series such as the SPI, SPEI and SGI."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["numpy", "scipy", "matplotlib", "pandas"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
testing = ["mypy", "pandas-stubs", "tox", "pytest", "pytest-cov"]
full = ["spei[testing]", "black[jupyter]"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
mypy_path = "src"

[[tool.mypy.overrides]]
module = ['matplotlib.*', 'scipy.stats.*']
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
